### PR TITLE
Fix n+1 problems and write integration tests

### PR DESCRIPTION
**Pull request by huzaifakhan0308**
- Write integration tests with Capybara gem.
- Secure app from n+1 problems.

**Note: I am solo in this project**

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @huzaifakhan0308 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that should be contributed to by you and your partner(s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brytebee** [comment]
@huzaifakhan0308 Kindly attach a snapshot of the message you received to work solo.

**Comment by huzaifakhan0308** [comment]
> @huzaifakhan0308 Kindly attach a snapshot of the message you received to work solo.

Screenshot 2023-05-18 001110

**Review by brytebee — APPROVED** [review]
Hi, @huzaifakhan0308 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great DB setup.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
